name: Mark Paulda El Paso Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51163
title: El Paso Stock Photography and Books
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#aeaeae'
    - '#465262'
    - '#fcfdd9'
    - '#692d0d'
  brandStrength: 0.875
  lightness: 0.7098497319966555
  saturation: 0.909724211320281
  rhythmicContrast: 0.39718509721569717
purpose: []
