name: Mark Paulda El Paso Photography
favicon: null
layout_spectrum: 0.37634
typography_spectrum: 0.30223
title: El Paso Stock Photography and Books
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f30014'
    - '#001756'
    - '#b89b87'
    - '#923c1f'
    - '#f14d39'
  brandStrength: 0.08645245851948857
  lightness: 0.7098497319966555
  saturation: 0.909724211320281
  rhythmicContrast: 0.39718509721569717
purpose: []
